[tool.poetry]
name = "deco-x50-firmware-unpack"
version = "0.1.0"
description = ""
authors = ["Huy Nguyen"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
bchlib = "^2.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
